"""Regenerate durable Kefu file payloads from stable database references."""
from __future__ import annotations

from uuid import UUID

from core.kefu_contracts import Artifact, ArtifactLike


class ArtifactUnavailable(LookupError):
    """A stored-bytes artifact has no stored row and rebuilding wasn't allowed."""


def load_artifact(request_log_id: UUID, doc_type: str, artifact_key: str, *, allow_rebuild: bool = True) -> ArtifactLike:
    """
    Rebuild an artifact identically after deferral or process restart.

    Doc types in core.kefu_delivery.STORED_ARTIFACT_DOC_TYPES are read back
    from kefu_artifact_blob (V37), never rebuilt from live data that may have
    changed since enqueue. A missing row there means either a delivery
    enqueued before V37 (rebuilt as before, still hash-checked by the
    sender) or a file purged after its retention (decision D8). Callers that
    must never rebuild -- the duplicate-message replay -- pass
    allow_rebuild=False and get ArtifactUnavailable instead.
    """
    from database import SessionLocal
    from core.kefu_delivery import STORED_ARTIFACT_DOC_TYPES
    from handlers.uchoice.pdf_stub import GeneratePdfStubHandler
    from models.kefu import KefuArtifactBlob
    from models.request_log import RequestLog
    from models.session import ConversationSession

    db = SessionLocal()
    try:
        if doc_type in STORED_ARTIFACT_DOC_TYPES:
            blob = db.get(KefuArtifactBlob, artifact_key)
            if blob is not None:
                return Artifact(bytes(blob.content), blob.filename, blob.content_type, blob.artifact_key)
            if not allow_rebuild:
                raise ArtifactUnavailable(f"stored {doc_type} {artifact_key} not found (expired or never stored)")
        log = db.get(RequestLog, request_log_id)
        if log is None:
            raise LookupError(f"request_log {request_log_id} not found")
        session = (
            db.query(ConversationSession)
            .filter(
                (ConversationSession.request_log_id == request_log_id)
                | (ConversationSession.session_id == log.origin_session_id)
            )
            .order_by(ConversationSession.created_at.asc())
            .first()
        )
        if session is None:
            raise LookupError(f"source session for request_log {request_log_id} not found")
        context = {
            "request_log_id": str(log.log_id),
            "serial_number": log.serial_number,
            "collected_fields": session.collected_fields or {},
        }
        if doc_type == "outbound_instruction":
            mapping = GeneratePdfStubHandler._build_outbound_instruction_artifact(context, db)
        elif doc_type == "invoice_workbook":
            from core.uchoice_invoice_export import build_invoice_artifact

            fields = session.collected_fields or {}
            mapping = build_invoice_artifact(
                db, fields.get("warehouse_code"), fields.get("start_month"), fields.get("end_month"), log.log_id
            )
        elif doc_type == "storage_history_workbook":
            from core.uchoice_storage_history_export import build_storage_history_artifact

            fields = session.collected_fields or {}
            mapping = build_storage_history_artifact(
                db, fields.get("warehouse_code"), fields.get("start_month"), fields.get("end_month"), log.log_id
            )
        elif doc_type == "label":
            # Deliberately NOT regenerated by calling create_label again --
            # that would create a SECOND, duplicate, separately-billed
            # carrier shipment. Reads the already-created label's own
            # bytes back from label_shipment.label_pdf instead (written
            # once, at creation time, by handlers/oms_create_workorder.py's
            # _record_label_shipment). See core/kefu_label_export.py.
            from models.customer import LabelShipment
            from core.kefu_label_export import build_label_artifact

            shipment = db.query(LabelShipment).filter_by(request_log_id=request_log_id).first()
            if shipment is None or shipment.label_pdf is None:
                raise RuntimeError(f"no stored label_pdf for request_log {request_log_id} -- cannot replay")
            mapping = build_label_artifact(shipment.label_pdf, shipment.carrier, log.serial_number, log.log_id)
        else:
            raise ValueError(f"unsupported durable artifact doc_type: {doc_type}")
        if mapping is None:
            raise RuntimeError(f"failed to regenerate {doc_type} for {request_log_id}")
        artifact = Artifact.from_mapping(mapping)
        if artifact.artifact_key != artifact_key:
            raise ValueError("artifact_key_mismatch")
        return artifact
    finally:
        db.close()
