from uuid import UUID
from datetime import datetime, timezone
from sqlalchemy.orm import Session as DBSession
from models.request_log import RequestLog


def create_log(
    db: DBSession,
    wechat_openid: str,
    group_id: UUID,
    service_type_id: UUID,
    raw_message: str,
    wechat_msg_id: str | None = None
) -> RequestLog:
    """
    Creates a request_log row when all fields are collected and the user
    is about to see the confirmation template.

    Serial number is auto-generated by the DB (generate_serial_number()).
    db.refresh() is called after commit so the serial_number is available
    on the returned object immediately.

    Status starts as 'processing' — updated to 'success' or 'failed'
    after the workflow runs.
    """
    log = RequestLog(
        wechat_openid=wechat_openid,
        group_id=group_id,
        service_type_id=service_type_id,
        status="processing",
        raw_message=raw_message,
        wechat_msg_id=wechat_msg_id
    )
    db.add(log)
    db.commit()
    db.refresh(log)  # loads DB-generated serial_number back into the object
    return log


def mark_success(
    db: DBSession,
    log_id: UUID,
    result: dict
) -> None:
    """
    Called by workflow_engine after all workflow steps complete successfully.
    Records the result payload (e.g. tracking number, label URL).
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "success"
    log.result       = result
    log.completed_at = datetime.now(timezone.utc)
    db.commit()


def mark_failed(
    db: DBSession,
    log_id: UUID,
    error_detail: str
) -> None:
    """
    Called by workflow_engine when any workflow step raises an exception.
    Records the error message for admin debugging via GET /admin/request-logs.
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "failed"
    log.error_detail = error_detail
    log.completed_at = datetime.now(timezone.utc)
    db.commit()
