from uuid import UUID
from datetime import datetime, timezone
from sqlalchemy.orm import Session as DBSession
from models.request_log import RequestLog


def create_log(
    db: DBSession,
    wechat_openid: str,
    group_id: UUID,
    service_type_id: UUID,
    raw_message: str,
    wechat_msg_id: str | None = None,
    source_channel: str = "smart_robot",
    submitted_by_staff_id: UUID | None = None,
    customer_id: UUID | None = None,
) -> RequestLog:
    """
    Creates a request_log row as soon as a service resolves at new_request
    time — logs every resolved request regardless of eventual outcome
    (confirmed, cancelled, or left to go stale).

    Serial number is auto-generated by the DB (generate_serial_number()).
    db.refresh() is called after commit so the serial_number is available
    on the returned object immediately.

    Status starts as 'pending' (awaiting customer confirm/cancel) —
    transitions to 'processing' on confirm, then 'success'/'failed' once the
    workflow finishes, or 'cancelled'/'timed_out'/'stale' if abandoned.

    source_channel and submitted_by_staff_id must be explicit at creation, not
    defaulted
    and patched in later -- a Kefu-originated request that briefly carried
    source_channel='smart_robot' would already be wrong for the window
    between creation and any later fix-up (included in Smart Robot's own
    scheduled jobs, excluded from the Kefu completion-notice query).
    """
    log = RequestLog(
        wechat_openid=wechat_openid,
        group_id=group_id,
        service_type_id=service_type_id,
        status="pending",
        raw_message=raw_message,
        wechat_msg_id=wechat_msg_id,
        source_channel=source_channel,
        submitted_by_staff_id=submitted_by_staff_id,
        customer_id=customer_id,
    )
    db.add(log)
    db.commit()
    db.refresh(log)  # loads DB-generated serial_number back into the object
    return log


def mark_success(
    db: DBSession,
    log_id: UUID,
    result: dict,
    commit: bool = True
) -> None:
    """
    Called by workflow_engine after all workflow steps complete successfully.
    Records the result payload (e.g. tracking number, label URL).

    commit=False lets a caller (core.workflow_engine's atomic DB phase) fold
    this status change into the same transaction as the storage deltas that
    preceded it, so a failure between this call and the caller's own commit
    rolls back both together instead of leaving mark_success durable alone.
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "success"
    log.result       = result
    log.completed_at = datetime.now(timezone.utc)
    if commit:
        db.commit()


def mark_failed(
    db: DBSession,
    log_id: UUID,
    error_detail: str,
    commit: bool = True
) -> None:
    """
    Called by workflow_engine when any workflow step raises an exception.
    Records the error message for admin debugging via GET /admin/request-logs.

    commit=False -- see mark_success's docstring for why this exists.
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "failed"
    log.error_detail = error_detail
    log.completed_at = datetime.now(timezone.utc)
    if commit:
        db.commit()


def mark_processing(db: DBSession, log_id: UUID) -> None:
    """Called right before workflow steps start executing (on confirm)."""
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status = "processing"
    db.commit()


def mark_cancelled(db: DBSession, log_id: UUID) -> None:
    """
    Called when the user explicitly cancels before confirming. Only valid for
    a log the cancelling session actually owns (not one it merely references
    via targets_existing_request) — see workflow_engine._handle_cancel.
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "cancelled"
    log.completed_at = datetime.now(timezone.utc)
    db.commit()


def mark_timed_out(db: DBSession, log_id: UUID) -> None:
    """
    Called by the session-expiry job when a session times out before the
    user confirmed. Only valid for a log the expiring session actually owns
    (not one it merely references via targets_existing_request) — see
    jobs/session_expiry.py.
    """
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "timed_out"
    log.completed_at = datetime.now(timezone.utc)
    db.commit()


def mark_stale(db: DBSession, log_id: UUID) -> None:
    """Called by the daily U-Choice job for processing requests past the 7-day threshold."""
    log = db.query(RequestLog).filter_by(log_id=log_id).first()
    if log is None:
        return
    log.status       = "stale"
    log.completed_at = datetime.now(timezone.utc)
    db.commit()
